export const GET_CONTACT='GET_CONTACY';
export const CONTACT_LOADING='CONTACT_LOADING';
export const EDIT_CONTACT='REMOVE_CONTACT';
export const REMOVE_CONTACT='REMOVE_CONTACT';
export const ADD_CONTACT='ADD_CONTACT'